#!/bin/bash
# Archive all the files in the current directory
# Just like archivealldirectories, but works on 
# a directory of files, presumably big zip or tar
# files
set -ex
find . -depth -maxdepth 1 -type f -print | while read i
do
    echo "-----------------------------------------------"
    /home/edt/bin/archivedirectory --encrypt "$i"
    /bin/rm -rf "$i"
    echo "Done with $i."
    echo "-----------------------------------------------"
    echo " "
    echo " "
done
